### ISSUE TITLE
反复加载时，出现空白页面

### ISSUE THREAD

**Issue by functionwell** [apicloudcom/UIMediaScanner#1]
首次使用该模块的open方法没有问题，第二次打开时就变成一片空白，没有资源可以选择了

代码如下：
`function uiMediaScan(type, cb){`
`            UIMediaScanner.open({`
`                type: type,`
`                max: 20 //多选上限`
`            }, function( ret, err ){`
`                if(!ret || !ret.eventType) return;`
`                if(ret.eventType === 'confirm'){`
`                    var sysType = api.systemType;`
`                    var retList = ret.list;`
`                    for(var i = 0; i < retList.length; i++){`
`                        var imgUrl = retList[i].path;`
`                        (function(imgUrl){`
`                            if(sysType === 'ios'){`
`                                UIMediaScanner.transPath({`
`                                    path: imgUrl`
`                                }, function(ret, err){`
`                                    if(ret){`
`                                        cb && cb(ret.path);`
`                                    }else{`
`                                        api.toast({msg: 'transPath err'});`
`                                    }`
`                                });`
`                            }else{`
`                                cb && cb(imgUrl);`
`                            }`
`                        })(imgUrl);`
`                    }`
`                }`
`            });`
`        };`

**Comment by sunzhengcuan** [comment]
推荐使用UIAlbumBrowser或WXPhotoPicker模块
