### ISSUE TITLE
ios 选择图片显示模糊

### ISSUE THREAD

**Issue by zzq5203796** [apicloudcom/UIMediaScanner#2]
在选择图片时，ios显示模糊

**Comment by chainthy** [comment]
那是未从iCloud下载完

**Comment by sunzhengcuan** [comment]
可以使用UIAlbumBrowser模块。https://github.com/apicloudcom/APICloud-Modules/tree/master/UIAlbumBrowser

**Comment by sunzhengcuan** [comment]
或者WXPhotoPicker模块 http://www.apicloud.com/mod_detail/123785
